### ISSUE TITLE
util/users.js 'find' command breaks with multiple users sharing the same name

### ISSUE THREAD

**Issue by PancakeTAS** [p2r3/epochtal#26]
Likely due to the steam name being the key of the object that is returned..

https://github.com/p2r3/epochtal/blob/d7644ac8c1faaf3f27af0f04a263953d6b8abaf5/util/users.js#L32

**Comment by p2r3** [comment]
The wording of the issue is a bit misleading - this only happens with the "find" command, which isn't relied upon anywhere in the backend, and is only really used for easier SteamID querying in the admin CLI.

Though honestly, I'll probably end up fixing this before that clarification matters to anyone.
