### ISSUE TITLE
Main elo leaderboard styling is weird

### ISSUE THREAD

**Issue by ArcherTheReal** [p2r3/epochtal#35]
For me personally it looks like stuff still wants to load but couldnt and it just cuts of at the end.

![image](https://github.com/user-attachments/assets/9051b062-1425-4c86-ba01-38ee348b7465)

I feel like it could be better done like insetting the actual data to make it never touch the sides, or adding a fade effect to the bottom and top or just like a border around it.

**Comment by ArcherTheReal** [comment]
also on the same note there is too much gap between this and the disable background animation

**Comment by p2r3** [comment]
We've played around with this element in testing, including adding the "fade" effect you mentioned. These changes were not favored and were rolled back and reiterated, leaving us with what we have now. Other solutions are simply not worth implementing for an otherwise functional element.

The gap is intentional.
